spring.application.name=smart-campus
server.port=8080



# Database (each member overrides in application-local.properties)
spring.datasource.url=jdbc:postgresql://ep-little-queen-a1t2rex3-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_TE1Fau0KeWfX

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# File upload
file.upload-dir=uploads/
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=15MB
