spring.application.name=smart-campus
server.port=8080



# Database (each member overrides in application-local.properties)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/smart_campus?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true} 
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.open-in-view=false

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.profiles.active=local

# File upload
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=15MB